FROM alpine

COPY script2.sh /script2.sh

COPY microservice2.py /usr/bin/acts.py

COPY static /usr/bin/static

CMD ["/script2.sh"]

ENV TEAM_ID=CC_370_410_417_739

#COPY script2.sh /script2.sh

#CMD ["/script2.sh"]
#ENV PYTHON_PATH=/usr/local/bin/ \
#    PATH="/usr/local/lib/python$PYTHON_VERSION/bin/:${PATH}"


#CMD ["cd","/usr/bin/"]

#CMD ["ls"]

#CMD ["python", "users.py"]

